// ============================================
// BIT SOFTWARE — ROUTE CONSTANTS
// ============================================

export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  SERVICES: '/services',
  SERVICES_IT: '/services/it-services',
  SERVICES_WEB: '/services/web-development',
  SERVICES_WEB_ECOMMERCE: '/services/web-development/ecommerce',
  SERVICES_WEB_EDUCATIONAL: '/services/web-development/educational',
  SERVICES_WEB_TRAINING: '/services/web-development/training-center',
  SERVICES_WEB_LMS: '/services/web-development/lms',
  SERVICES_WEB_SUPPLY: '/services/web-development/supply-company',
  SERVICES_WEB_MANPOWER: '/services/web-development/manpower',
  SERVICES_WEB_CUSTOM: '/services/web-development/custom-website',
  SERVICES_WEB_DROPSHIP: '/services/web-development/drop-shipping',
  SERVICES_ERP: '/services/erp-software',
  SERVICES_MOBILE: '/services/mobile-apps',
  SERVICES_SOCIAL: '/services/social-media',
  SERVICES_LOGO: '/services/logo-design',
  SERVICES_GRAPHICS: '/services/graphics-design',
  SERVICES_IT_MGMT: '/services/it-management',
  SERVICES_MARKETING: '/services/online-marketing',
  SERVICES_GMB: '/services/google-my-business',
  SERVICES_HOSTING: '/services/domain-hosting',
  PORTFOLIO: '/portfolio',
  BLOG: '/blog',
  BLOG_POST: '/blog/:slug',
  CONTACT: '/contact',
  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  AUTH_FORGOT: '/auth/forgot-password',
  DASHBOARD: '/dashboard',
  DASHBOARD_SERVICES: '/dashboard/services',
  DASHBOARD_SERVICES_ADD: '/dashboard/services/add',
  DASHBOARD_OFFERS: '/dashboard/offers',
  DASHBOARD_LEADS: '/dashboard/leads',
  DASHBOARD_ORDERS: '/dashboard/orders',
  DASHBOARD_USERS: '/dashboard/users',
  DASHBOARD_ANALYTICS: '/dashboard/analytics',
  DASHBOARD_SETTINGS: '/dashboard/settings',
};
